name: appwrite_offline_example
description: Example app for appwrite_offline package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite_offline:
    path: ../
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  flutter_data: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
